version: '3.7'
services:

  webserver:
    image: nginx:alpine
    container_name: badge-poser-webserver
    working_dir: /application
    depends_on:
      - php-fpm
    volumes:
      - .:/application:cached
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./var/log/nginx/:/var/log/nginx:cached
    ports:
      - '8001:80'

  php-fpm:
    build:
      context: docker/dev/php-fpm
      network: host
    container_name: badge-poser-php-fpm
    working_dir: /application
    depends_on:
      - redis
    volumes:
      - .:/application:cached
      - ./docker/dev/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini:ro
    ports:
        - "9000"

  node:
    container_name: badge-poser-node
    image: node:12-alpine
    user: "node"
    volumes:
      - .:/application:cached
    working_dir: /application

  redis:
    image: redis:alpine
    container_name: badge-poser-redis
    ports:
      - "6379:6379"
